### ISSUE TITLE
time_key

### ISSUE THREAD

**Issue by geek876** [atomita/fluent-plugin-aws-elasticsearch-service#10]
Does this plugin support `time_key` feature as with the default elastic search plugin https://github.com/uken/fluent-plugin-elasticsearch ?

**Comment by atomita** [comment]
Hi @geek876 ,

This plugin is just overriding the connection part of "the fluent-plugin-elasticsearch".
Probably, I think "time_key" to work.

Please try and report!

Regards,
atomita

**Comment by geek876** [comment]
Hi, yes it works. Thanks.

**Comment by atomita** [comment]
Thank you for report!
