### ISSUE TITLE
Does this support version 1.5 and 2.3 of elasticsearch?

### ISSUE THREAD

**Issue by john-delivuk** [atomita/fluent-plugin-aws-elasticsearch-service#19]
As soon as I deploy this my ElasticSearch cluster goes unhealthy(yellow state). I did use 2.3 and wanted to confirm if this was supported by the plugin.

**Comment by mpas** [comment]
I am using it on 2.3 and it seems to work fine.

**Comment by davidgacc** [comment]
I am using fluent-plugin-aws-elasticsearch-service on ES 5.3 and it seems not working.
I was wondering if someone could check if https://rubygems.org/gems/fluent-plugin-aws-elasticsearch-service supports AWS Elasticsearch 5.3 ?

**Comment by cosmo0920** [comment]
Could you check version incompatibility between ES and elasticsearch-ruby?
https://github.com/elastic/elasticsearch-ruby#compatibility

If you want to communicate to ES 5.x, you shall use elasticsearch-ruby 5.x.
Otherwise, Fluentd cannot push events there.

**Comment by cosmo0920** [comment]
This is Old issue. Closing.
