### ISSUE TITLE
Plan for proxy_uri support

### ISSUE THREAD

**Issue by ronanbuke** [atomita/fluent-plugin-aws-elasticsearch-service#26]
Are there any plans on adding proxy_uri support for connecting to aws elasticsearch through a proxy ?

**Comment by cosmo0920** [comment]
AWS Elasticsearch Service plugin inherits ES plugin and it depends on faraday gem for transport backend.
Faraday gem searches proxies with `URI.find_proxy`.
You can setup proxy with `http_proxy`, `ftp_proxy`, `no_proxy` (also large letters OK) environment variables.

**Comment by cosmo0920** [comment]
Already supported. Closing.
