### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by tyronedougherty** [atomita/fluent-plugin-aws-elasticsearch-service#3]
Is it possible for the plugin use a dynamic configuration?

For example, have the match pattern of fluentd specify a type name in elasticsearch? The Fluentd elasticsearch plugin (which this plugin extends?) [allows this to happen.](https://github.com/uken/fluent-plugin-elasticsearch/#dynamic-configuration)

I've had a play around with the source and have not successfully been able to get it working with the dynamic plugin, but I'm not a ruby dev. Does anyone know if this is possible or am I just shooting in the dark?

Many thanks!

**Comment by atomita** [comment]
hi @tyronedougherty .

Sorry, do not supported a dynamic configuration.

I do not fully understand yet a dynamic configuration.

thanks!

**Comment by tyronedougherty** [comment]
For anyone that comes across this in the future that wants to know how to do a dynamic configuration for fluentd, I managed to solve this problem by installing [fluent-plugin-forest](https://github.com/tagomoris/fluent-plugin-forest), which allows you to use the tag_parts variable in your config.

My fluentd config now looks similar to the following
```
<match testpattern.**>
        type forest
        subtype "aws-elasticsearch-service"
        <template>
            type_name ${tag_parts[1]}
            logstash_format true
            flush_interval "10s"
            <endpoint>
                url "http:/xxx.ap-southeast-2.es.amazonaws.com:80"
                region "ap-southeast-2"
                access_key_id "xxx"
                secret_access_key "xxx"
            </endpoint>
        </template>
</match>
```

Hope this solves someones future problems! :smile:
