### ISSUE TITLE
How can I set the _type from the tag?

### ISSUE THREAD

**Issue by marksawersw** [atomita/fluent-plugin-aws-elasticsearch-service#37]
Hello. 

I'd like to send in the _type dynamically based on the tag, as in:

    <match **>
    @type aws-elasticsearch-service
    type_name ${tag}
    ...
    </match>

but literal ${tag} shows in the _type field kibana. 

Are there any variables that work there?

Also tried setting the following:

    include_tag_key true
    tag_key "_type"

but that didn't work.

Suggestions?

Thanks!
Mark

**Comment by cosmo0920** [comment]
Hi. 
This is fluent-plugin-elasticsearch plugin's issue.
Could you report your issue in [fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch)?

**Comment by marksawersw** [comment]
I see it's been raised in [issue 53](https://github.com/uken/fluent-plugin-elasticsearch/issues/53) and closed with recommendation to use [fluent-plugin-forest](https://github.com/tagomoris/fluent-plugin-forest). I'll try that.

**Comment by cosmo0920** [comment]
For v0.12, it is correct.
For v0.14, this should treat as a bug of fluent-plugin-elasticsearch.

**Comment by marksawersw** [comment]
Ok I've opened [Issue 330](https://github.com/uken/fluent-plugin-elasticsearch/issues/330) on the base project.
