### ISSUE TITLE
gem install fails for fluent-plugin-aws-elasticsearch-service

### ISSUE THREAD

**Issue by randomyug** [atomita/fluent-plugin-aws-elasticsearch-service#39]
Hi,

I am building an AMI ( with pre installed fluentd and this plugin ). It was working fine for several months. But recently it seems to be broken. I see that dev activity picked up again. 

I was using this command
/usr/sbin/td-agent-gem install fluent-plugin-aws-elasticsearch-service

But now it fails with compilation of strptime-0.1.9 and in the corresponding
mkmf.log I see gcc trying to compile something. We do not have gcc in our AMI. 

Is this expected ? Dependency on strptime-0.1.9 .. is it newly added?

How do I install the latest fluent-plugin-aws-elasticsearch-service ?

As a workaround, I am using this command
/usr/sbin/td-agent-gem install fluent-plugin-aws-elasticsearch-service -v 0.1.6

But want to use the latest fluent-plugin-aws-elasticsearch-service

**Comment by cosmo0920** [comment]
> Is this expected ? Dependency on strptime-0.1.9 .. is it newly added?
> 
> How do I install the latest fluent-plugin-aws-elasticsearch-service ?

Yes. It is expected.
Because Fluentd v0.14 depends on [strptime](https://github.com/nurse/strptime) gem which is written in C.
*strptime* is introduced in Fluentd v0.14.0 for supporting EventTime msgpack extension type in Fluentd.

You should install ruby-dev (or ruby-devel?) package and gcc related package and then, remove development packages.

**Comment by sriramsv** [comment]
I tried to install ruby-devel and gcc related packages, but still install fails,
I also tried install strptime gem 2.3.0
I am using fluentd-1.0.2.

**Comment by cosmo0920** [comment]
fluent-plugin-aws-elasticsearch-service stop to depends a lots of aws-sdk related gems.
Could you try fluent-plugin-aws-elasticsearch-service v2.0.0 in your environment?

**Comment by cosmo0920** [comment]
#49 is merged. Closing.
