### ISSUE TITLE
Passing custom headers

### ISSUE THREAD

**Issue by gvishnutej** [atomita/fluent-plugin-aws-elasticsearch-service#40]
Hi,
Is there a config to pass custom request headers to elastic search? I need to pass API key as a request header to elastic search api gateway.

Thanks,
Vishnu Tej

**Comment by cosmo0920** [comment]
fluent-plugin-elasticsearch v3.1.1 and fluent-plugin-aws-elasticsearch-service v2.0.0 support custom headers.

Here is an example to use custom headers:

```
custom_headers {"token":"value"}
```

**Comment by cosmo0920** [comment]
Already supported in based ES plugin. Closing.
