### ISSUE TITLE
Gem install is slow

### ISSUE THREAD

**Issue by castro1688** [atomita/fluent-plugin-aws-elasticsearch-service#48]
As it stands fluent-plugin-aws-elasticsearch-service requires the aws-sdk gem. This includes 30+ aws-sdk-* items. 

With sdk version 3 there is the ability to install specific modules. https://github.com/aws/aws-sdk-ruby/blob/master/README.md

**Comment by dpgaspar** [comment]
Same problem here!

**Comment by thadamski** [comment]
I too had/have the slow gem install issue. I was installing via chef with the `td-agent` cookbook, and I was able to get them gem installing fast by reducing the aws dependencies (as @castro1688 pointed out) to only what was needed (`aws-sdk-core`), rebuilding the gem, and then doing a local install. If you would like to do the same, check out the PR description (you'll probably want to bump the version in the .gemspec first): https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/pull/49
