### ISSUE TITLE
Unable to activate faraday_middleware-aws-sigv4-0.2.5, because faraday-0.15.4 conflicts with faraday (< 0.15, >= 0.9) (Gem::ConflictError)

### ISSUE THREAD

**Issue by daijongkim** [atomita/fluent-plugin-aws-elasticsearch-service#59]
#### Problem
don't start td-agent

Starting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate faraday_middleware-aws-sigv4-0.2.5, because faraday-0.15.4 conflicts with faraday (< 0.15, >= 0.9) (Gem::ConflictError)

#### Steps to replicate

service td-agent start

#### Expected Behavior or What you need to ask
 dependency version change 
 as-is : faraday_middleware-aws-sigv4-0.2.5
 to-be: faraday_middleware-aws-sigv4-0.3.0

#### Using Fluentd and ES plugin versions

* OS version
  * Linux ip-10-24-170-25 4.14.104-78.84.amzn1.x86_64 #1 SMP Mon Mar 4 19:19:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Fluentd version
  * td-agent 1.3.3
* AWS ES Service plugin version
  * fluent-plugin-aws-elasticsearch-service (2.1.0)
* IAM policies for AWS ES Service (optional)
* ES version (optional)

**Comment by Evan-S** [comment]
I have this same problem using td-agent as of freshly rebuilding my containers today.

I got it to start by running `td-agent-gem update` for now. I haven't tested very thoroughly if that breaks anything else, so use it at your own risk if you have other plugins installed.

**Comment by daijongkim** [comment]
I solved it like this 
`td-agent-gem update faraday_middleware-aws-sigv4`

> I have this same problem using td-agent as of freshly rebuilding my containers today.
> 
> I got it to start by running `td-agent-gem update` for now. I haven't tested very thoroughly if that breaks anything else, so use it at your own risk if you have other plugins installed.

**Comment by cosmo0920** [comment]
Should be resolved in #61.
