### ISSUE TITLE
Is shard configuration possible while creating index

### ISSUE THREAD

**Issue by manojverma-net** [atomita/fluent-plugin-aws-elasticsearch-service#69]
#### Question

 Is there any property or something which I can use to setup index shard like no of shard for index. 

#### Expected Behavior or What you need to ask

```
<match **>
   @type aws-elasticsearch-service
   @id out_aws_es
   @log_level debug
   include_tag_key true
   <endpoint>
     url "#{ENV['ELASTICSEARCH_ENDPOINT']}"
     region "#{ENV['ELASTICSEARCH_REGION']}"
   </endpoint>
   logstash_format 'true'
   index_name  'logstash'
   type_name 'fluentd'

   shard_count 1  <----- looking for this flag.
   
</match>
```

**Comment by manojverma-net** [comment]
@atomita @cosmo0920  - please provide your valuable input on this.

**Comment by cosmo0920** [comment]
We won't plan to support it.
We can specify it with `number_of_shards` on Elasticsearch index templates:

```json
{
    "template" : "your-awesome-indices-*",
    "settings" : {
        "number_of_shards" : 1
    }
}
```

ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html
