### ISSUE TITLE
Change fluent-plugin-elasticsearch dependency to fluent-plugin-opensearch

### ISSUE THREAD

**Issue by stevehipwell** [atomita/fluent-plugin-aws-elasticsearch-service#78]
#### Problem

The current version will not work with AWS OpenSearch (the new name for AWS ElasticSearch) unless the ElasticSearch dependency is locked to an old one prior to the re-licencing.

#### Steps to replicate

Use this plugin, without locking the ElasticSearch dependencies, against AWS OpenSearch/ElasticSearch and it will error.

#### Expected Behavior or What you need to ask

It should work so this plugin should switch to using the [fluent-plugin-opensearch](https://github.com/fluent/fluent-plugin-opensearch).

**Comment by cosmo0920** [comment]
We needn't inherit fluent-plugin-opensearch.
And we still need to maintain this plugin for old AWS OpenSearch instances before Elasticsearch 7.10.

see: https://github.com/uken/fluent-plugin-elasticsearch/issues/915#issuecomment-1012244803
