### ISSUE TITLE
Parametrizing variables in the config

### ISSUE THREAD

**Issue by krishnatrivedi** [atomita/fluent-plugin-aws-elasticsearch-service#9]
Greetings,

First off, thank you for a great plugin. This has helped me quite a bit.

The issue I'm raising is to figure out a way to parametrize or variablize the tag into the match function. 

I found this plugin:  https://github.com/tagomoris/fluent-plugin-forest

It's suggested by the dev of this:  https://github.com/uken/fluent-plugin-elasticsearch

When I use the implementation of the forest plugin, nothing gets sent to ElasticSearch. If I don't use the forest plugin, then trying to use 'logstash_prefex ${tag}' gives the index a prefix that's explicitly ${tag}.

Here's a sample of what I'm trying to do with forest:

```fluentd
<match es.**>
  type forest
  subtype copy

  <store>
    type "aws-elasticsearch-service"
    logstash_format true
    logstash_prefix ${tag}
    include_tag_key true
    tag_key "@log_name"
    log_level info
    flush_interval "5s"

    <endpoint>
      url "xxx"
      region "us-east-1"
      access_key_id "xxx"
      secret_access_key "xxx"
    </endpoint>
  </store>
</match>
```

Any ideas?

Thanks,
Krishna T.

**Comment by atomita** [comment]
Hi, @krishnatrivedi 

The `${tag}` is available, I think that in the template tag.

```fluentd
<match es.**>
  type forest
  subtype "aws-elasticsearch-service"

  <template>
    logstash_format true
    logstash_prefix ${tag}
    include_tag_key true
    tag_key "@log_name"
    log_level info
    flush_interval "5s"

    <endpoint>
      url "xxx"
      region "us-east-1"
      access_key_id "xxx"
      secret_access_key "xxx"
    </endpoint>
  </template>
</match>
```

**Comment by krishnatrivedi** [comment]
Thank you @atomita ! Your tip helped. 

I missed the whole '<template>' bit from the documentation. For your reference (and anyone else's), here's my full config section (with your plugin and the s3 plugin + forest plugin):

<match es.**>
  type forest
  subtype copy

  <template>
    <store>
      type "aws-elasticsearch-service"
      logstash_format true
      logstash_prefix ${tag}
      include_tag_key true
      tag_key "@log_name"
      log_level info
      flush_interval "5s"

      <endpoint>
        url "xxx"
        region "us-east-1"
        access_key_id "xxx"
        secret_access_key "xxx"
      </endpoint>
    </store>

    <store>
      type "s3"
      aws_key_id "xx"
      aws_sec_key "xxx"
      s3_bucket "xxx"
      s3_region "us-east-1"
      s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
      path logs/${tag}/
      buffer_path "/var/log/td-agent/buffer/${tag}/s3"
      time_slice_format "%Y-%m-%d/%H"
      time_slice_wait "5m"
      utc
      log_level trace
    </store>
  </template>
</match>

Thanks again!

Regards,
Krishna T.
